---
title: "niche_species_uniref"
author: "Sherlyn Weng, Oriane Moyne"
date: "2023-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r}
library(stringr)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(reshape)
library(reshape2)
library(data.table)
library(dplyr)
library(tidyr)
library(scales)
```


## Data Import

```{r}
# load and format feature table
data <- fread("./data/counts_species_uniref.tsv",
            sep="\t",
            dec=".",
            header = TRUE,
            stringsAsFactors = FALSE,
            na.strings = "",
            check.names = FALSE) %>% 
  as.data.frame() %>% 
  dplyr::rename(gene = Name) %>% 
  rename_with(~ str_replace(., "_wol_above30", ""), everything()) %>%
  rename_with(~ str_replace(., "mi04t", "MI04T"), everything()) %>% 
  mutate(genus = str_split(`#FeatureID`, "\\|", simplify = TRUE)[, 1]) %>% 
  select(-`#FeatureID`) %>% 
  select(genus, gene, everything()) # 105,027 × 50

# aggregate by gene
data <- aggregate(data[, str_detect(colnames(data), 'meta')], by = list(data$genus, data$gene), sum) %>%  # 57,830 × 50
  dplyr::rename(genus = Group.1, gene = Group.2)
```

## Data Cleaning

```{r}
# keep the deeply sequenced metaG
list_metag_deep <- data %>% select(matches("metaG")) %>% colSums() %>% as.data.frame() %>% setNames("colsum") %>% 
  arrange(desc(colsum)) %>% 
  filter(colsum > 600000) %>% 
  rownames

list_metag_shallow <- data %>% select(matches("metaG")) %>% colSums() %>% as.data.frame() %>% setNames("colsum") %>% 
  arrange(desc(colsum)) %>% 
  filter(colsum < 600000) %>% 
  rownames

data <- data %>% select(-list_metag_shallow)

# swap samples backd due to errors in labeling
colnames(data)[colnames(data) == "MI04T1_fru_1_metaG_S99"] <- "mi04t2_ref_1_metaG_S102"
colnames(data)[colnames(data) == "MI04T2_ref_1_metaG_S102"] <- "mi04t1_fru_1_metaG_S99"

colnames(data)[colnames(data) == "MI04T1_fru_1_metaT_S46"] <- "mi04t2_ref_1_metaT_S48"
colnames(data)[colnames(data) == "MI04T2_ref_1_metaT_S48"] <- "mi04t1_fru_1_metaT_S46"

colnames(data) <- str_replace(colnames(data), "mi04t", "MI04T")
```


```{r}
# 43 unique species
length(unique(data$genus))

# 22,823 unique genes
length(unique(data$gene))

## ref only 
data_ref <- data %>% 
  select(genus, gene, matches("_ref_")) %>% 
  filter(rowSums(select_if(., is.numeric), na.rm = TRUE) != 0) 

# 43 unique species
length(unique(data_ref$genus))
# 21,557 unique genes
length(unique(data_ref$gene))
```


## Examine B. breve
```{r}
data %>% 
  #filter(grepl('longum', genus)) %>% 
  filter(grepl('ylose', gene))
```


## Normalization

```{r}
# cpm normalization
data_cpm <- data
data_cpm[, str_detect(colnames(data_cpm), "meta")] <- apply(data_cpm[, str_detect(colnames(data_cpm), "meta")], 2, function(x) x/sum(x) * 1000000)

# check
apply(data_cpm[, 3:ncol(data_cpm)], 2, summary)
barplot(colSums(data_cpm[, 3:ncol(data_cpm)]), las=2)
```


## Multiomics Flitering

```{r}
# Create separate matrices for each omic
metaG_mat <- data_cpm[, str_detect(colnames(data_cpm), "metaG")]
colnames(metaG_mat) <- str_split(colnames(metaG_mat), "_meta", simplify = TRUE)[,1]
metaT_mat <- data_cpm[, str_detect(colnames(data_cpm), "metaT")]
colnames(metaT_mat) <- str_split(colnames(metaT_mat), "_meta", simplify = TRUE)[,1]
metaRS_mat <- data_cpm[, str_detect(colnames(data_cpm), "metaRS")]
colnames(metaRS_mat) <- str_split(colnames(metaRS_mat), "_meta", simplify = TRUE)[,1]

# order them the same
metaG_mat <- metaG_mat[, colnames(metaG_mat)]
metaT_mat <- metaT_mat[,  colnames(metaG_mat)]
metaRS_mat <- metaRS_mat[,  colnames(metaG_mat)]

# Rename columns
colnames(metaG_mat) <- paste(colnames(metaG_mat), "metaG", sep = "_")
colnames(metaT_mat) <- paste(colnames(metaT_mat), "metaT", sep = "_")
colnames(metaRS_mat) <- paste(colnames(metaRS_mat), "metaRS", sep = "_")

# Filtering

 # metaT_mat[metaG_mat == 0] <- 0
 # metaRS_mat[metaG_mat == 0] <- 0
# metaRS_mat[metaT_mat == 0] <- 0

TE_mat <- metaRS_mat / metaT_mat

colnames(TE_mat) <- str_replace(colnames(TE_mat), "_metaRS", "_TE")

# NaN produced when 0/0
TE_mat[is.na(TE_mat)] <- 0

# Inf produced when x/0
is.na(TE_mat) <- sapply(TE_mat, is.infinite)
TE_mat[is.na(TE_mat)] <- 0
#TE_mat[TE_mat<1] <- 0

data_cpm <- data.frame(cbind(data_cpm[, 1:2], metaG_mat, metaT_mat, metaRS_mat, TE_mat))
```


## Import Proteins

### Select Importer Genes
```{r, fig.height=16, fig.width=20}
# select import proteins
niche <- data_cpm %>% 
  filter(
    grepl("ransport", gene) |
    grepl("mport", gene) |
    grepl("ptake", gene) |
    grepl("ermease", gene)) %>% 
  filter(
    !grepl("Autoinducer 2", gene),  # exclude: no info about substrates
    !grepl("biotic", gene),         # exclude: those are to export
    !grepl("utative", gene))        # exclude: putative genes


# # number of unique importer genes in total
# length(unique(niche$gene)) # 2,382
```


### Table Formating For Plots
```{r}
molten <- reshape::melt(niche, id.vars = c("genus", "gene"))
molten$omic <- str_split(molten$variable, "_", simplify = TRUE)[,4]
molten$omic <- ordered(molten$omic, levels = c("metaG", "metaT", "metaRS", "TE"))
molten$condition <- str_split(molten$variable, "_", simplify = TRUE)[,2]
molten$condition <- str_replace(molten$condition, "fru", "BHI + Fructose")
molten$condition <- str_replace(molten$condition, "ref", "BHI")
molten$condition <- ordered(molten$condition, levels = c("BHI", "BHI + Fructose"))
```


### Overvall importer genes profile for T1
```{r, fig.height=16, fig.width=20}
# T1, all importer genes, TE, BHI condition
molten %>% 
  filter(
    grepl("T1", variable),      # select individual
    omic == "TE",               # select omics
    condition == "BHI",         # select condition
    value > 0) %>%              # filter on count values
  mutate(value_log = log(value)) %>% 
  ggplot(aes(x = gene, y = genus, fill= value_log)) + 
           geom_tile() + 
           scale_y_discrete(expand=c(0, 0)) +
           facet_wrap(.~ condition + omic, ncol = 4) +
           scale_fill_gradient(low="gold", high="red", na.value = "lightgray") +
           theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust = 1)) + 
           theme(text = element_text(size = 13))
  
```


```{r, fig.height=10, fig.width=20}
# for publication
molten %>% 
  filter(
    grepl('ructose', gene),
    !grepl('ructoselysine', gene),
    !grepl("Drancourtella", genus),
    grepl("T1", variable),      # select individual
    omic == "TE",               # select omics
    condition == "BHI",         # select condition
    value > 0) %>%              # filter on count values
  mutate(value_log = log(value)) %>% 
  ggplot(aes(x = genus, y = gene, fill= value_log)) + 
           geom_tile() + 
           scale_y_discrete(expand=c(0, 0)) +
           #facet_wrap(.~ condition + omic, ncol = 4) +
           labs(x = "", y = "", fill = "log(metaRS)") +
           scale_fill_gradient(low="gold", high="red", na.value = "lightgray") +
           theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust = 1)) + 
           theme(axis.text = element_text(size = 17, color = "black")) + 
           theme(text = element_text(size = 17, color = "black"))

#ggsave("./out/niche_kegg_species_t1_fructose.svg", height = 12, width = 20)

molten %>% 
  filter(
    grepl('ylose', gene),
    !grepl('zzz', gene),        # select genes to exclude
    !grepl("Drancourtella", genus),
    grepl("T1", variable),      # select individual
    omic == "TE",               # select omics
    condition == "BHI",         # select condition
    value > 0) %>%              # filter on count values
  mutate(value_log = log(value)) %>% 
  ggplot(aes(x = genus, y = gene, fill= value_log)) + 
           geom_tile() + 
           scale_y_discrete(expand=c(0, 0)) +
           #facet_wrap(.~ condition + omic, ncol = 4) +
           labs(x = "", y = "", fill = "log(metaRS)") +
           scale_fill_gradient(low="gold", high="red", na.value = "lightgray") +
           theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust = 1)) + 
           theme(axis.text = element_text(size = 17, color = "black")) + 
           theme(text = element_text(size = 17, color = "black"))

#ggsave("./out/niche_kegg_species_t1_xylose.svg", height = 10, width = 20)
```


## Primary Targets

```{r}
# customized function
primary_targets <- function(individual,           # e.g."T1"/"T2"
                            value_cutoff,         # value > value_cutoff e.g. 10
                            substrate_to_include, # substrate to include e.g. "ructose"
                            substrate_to_exclude  # put "zzz" if no substrate to exclude
                            ){
  res <- molten %>% 
    filter(
      grepl(substrate_to_include, gene),
      !grepl(substrate_to_exclude, gene),
      !grepl("Drancourtella", genus),
      grepl(individual, variable),
      omic == "TE",
      condition == "BHI",
      value > value_cutoff) %>% 
      arrange(desc(value)) %>% 
      group_by(genus, gene) %>%
      summarize(average_value = mean(value, na.rm = TRUE), .groups = "drop") %>%
      arrange(desc(average_value))
  
  targets <- res %>% 
    distinct(genus) %>% 
    pull(genus)
  
  return(list(res = res, targets = targets))
  print(res)
  #return(targets)
}
```

### MI04T1
```{r}
# fructose
pt_fructose <- primary_targets("T1", 0, 'ructose', 'ructoselysine')
write.csv(pt_fructose$res, "./out/tables/species_uniref_fructose.csv")

# xylose
pt_xylose <- primary_targets("T1", 0, 'ylose', 'zzz')
write.csv(pt_xylose$res, "./out/tables/species_uniref_xylose.csv")

pt_fructose
pt_xylose
```



