---
title: "SynCom Community Modifs Abundance Analysis"
author: "Oriane Moyne"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r, message = FALSE}
# Packages I commonly use
library(stringr)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(reshape)
library(reshape2)
library(gplots)
library(ggpubr)
library(cowplot)
```

## Data import 

```{r}
# Count tables with taxonomy annotations (Woltka gotu output)
syncom <- read.table("/home/moyne/Moyne_disk/Soil_project/Final_datasets/PROBIOTOCS_EXPT_3/Probiotics_3_Syncom_formatted_filtered_corrected_RPKM.tsv", 
                    sep="\t", 
                    dec=".", 
                    header = TRUE, 
                    stringsAsFactors = FALSE, 
                    na.strings = NA, 
                    check.names = FALSE, 
                    comment.char = "")
syncom$genus_strain <- str_split(syncom$genus_strain, "_", simplify = TRUE)[,1]

syncom <- syncom[!syncom$genus_strain%in%c("Bacillus", "Terrabacter"), ]
syncom$genus_strain <- str_replace(syncom$genus_strain, "Chitinophagaceae", "Niastella")


colnames(syncom) <- c(colnames(syncom)[1:3], paste(str_split(colnames(syncom[, 4:ncol(syncom)]), "_", simplify = TRUE)[,1], str_split(colnames(syncom[, 4:ncol(syncom)]), "_", simplify = TRUE)[,2], sep = "_"))
colnames(syncom) <- c(colnames(syncom)[1:3],  paste("X", colnames(syncom[, 4:ncol(syncom)]), sep = ""))
```

```{r, eval = FALSE}
PCA(t(syncom[, 4:ncol(syncom)]))
```

What are the unannotated ones?

```{r, eval = TRUE, fig.height = 3, fig.width=4, eval = FALSE}
test3 <- aggregate(syncom[, 4:ncol(syncom)], by = list(syncom$genus_strain), sum)
test3$X1_av <- apply(test3[, str_detect(colnames(test3), "X1")], 1, function(x)mean(x, na.rm = TRUE))

vec_col <- c("seagreen4", "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  "orange", "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3", "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")

ggplot(test3, aes(x = X1_av, y = XAGGCAGAA_GATGCAGT)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("Abundance in SynCom (RPKM)") +
  ylab("Abundance in unannotated sample (RPKM)") 

ggplot(test3, aes(x = X1_av, y = XAGGCAGAA_GATGCAGT)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("Abundance in SynCom (RPKM)") +
  ylab("Abundance in unannotated sample (RPKM)") 

## No Arthro. These are reads from 4_1 that did not demultiplex properly (see also PCA plot). 

ggplot(test3, aes(x = X1_av, y = XTCCTGAGC_GATGCAGT)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("Abundance in SynCom (RPKM)") +
  ylab("Abundance in unnanotated sample (RPKM)") 

## More Burkho. This is 7a_2 (see also PCA plot). 
```

```{r}
colnames(syncom) <- c(colnames(syncom)[1:3],
                      ifelse(str_detect(colnames(syncom[, 4:ncol(syncom)]), "TCCT"), "X7a_2",
                            ifelse(str_detect(colnames(syncom[, 4:ncol(syncom)]), "AGGC"), "XXXX",
                            colnames(syncom[, 4:ncol(syncom)])
                            ))
)
```



## Aggregate by strain

```{r}
syncom_agg <- syncom[, c(3:ncol(syncom))]
syncom_agg <- aggregate(syncom_agg[, 2:ncol(syncom_agg)], by = list(syncom_agg$genus_strain), sum)
```

## PCA plot

```{r, eval = TRUE, fig.width=16}
for_pca <- data.frame(t(syncom_agg[, 2:ncol(syncom_agg)]))
colnames(for_pca) <- paste(syncom_agg$Group.1)
                             
pca <- PCA(for_pca)

fviz_pca_ind(pca)
fviz_pca_biplot(pca)
```



## Abundance plots


```{r}
data_plots <- reshape::melt(syncom_agg)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Sample <- as.character(data_plots$Sample)

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]

data_plots$Concentration <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
```



```{r, eval = TRUE}
vec_col1 <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  
           "orange",   "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3",  "mediumvioletred","mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")
```


```{r, fig.height=8, fig.width=8}
ggplot(data_plots, aes(fill=Taxon, y=count, x=Replicate)) + 
    geom_bar(stat="identity") +
    scale_fill_manual(values = vec_col1) +
    facet_wrap(.~Community, ncol = 6, scales = "free_x") +
   theme(text = element_text(size = 15)) +
  labs(y = "RPKM") 

ggplot(data_plots, aes(fill=Taxon, y=count, x=Replicate)) + 
    geom_bar(stat="identity", position = "fill") +
    scale_fill_manual(values = vec_col1) +
    facet_wrap(.~Community, ncol = 6, scales = "free_x") +
   theme(text = element_text(size = 15)) +
  labs(y = "RPKM") 

# Replicates look nice
```

#--------------------------------

Correlation between controls

```{r, eval = FALSE}
test3 <- aggregate(syncom[, 4:ncol(syncom)], by = list(syncom$genus_strain), sum)

cor(test3[, str_detect(colnames(test3), "X1_")])

ggplot(test3, aes(x = X1_1, y = X1_3)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col1) +
  geom_abline(intercept = 0, slope = 1) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    ##stat_regline_equation(label.y = 500, aes(label = ..rr.label..)) +
    theme(legend.position = "none")  +
  xlab("Control 1 (RPKM)") +
  ylab("Control 2 (RPKM)") 

ggplot(test3, aes(x = X1_1, y = X1_4)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col1) +
  geom_abline(intercept = 0, slope = 1) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    ##stat_regline_equation(label.y = 500, aes(label = ..rr.label..)) +
    theme(legend.position = "none")  +
  xlab("Control 1 (RPKM)") +
  ylab("Control 3 (RPKM)") 

ggplot(test3, aes(x = X1_3, y = X1_4)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col1) +
  geom_abline(intercept = 0, slope = 1) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    ##stat_regline_equation(label.y = 500, aes(label = ..rr.label..)) +
    theme(legend.position = "none")  +
  xlab("Control 2 (RPKM)") +
  ylab("Control 3 (RPKM)") 
```


```{r}
test3 <- aggregate(syncom[, 4:ncol(syncom)], by = list(syncom$genus_strain), sum)

test3$X1_av <- apply(test3[, str_detect(colnames(test3), "X1")], 1, function(x)mean(x, na.rm = TRUE))
test3$X2_av <- apply(test3[, str_detect(colnames(test3), "X2")], 1, function(x)mean(x, na.rm = TRUE))
test3$X3_av <- apply(test3[, str_detect(colnames(test3), "X3")], 1, function(x)mean(x, na.rm = TRUE))
test3$X4_av <- apply(test3[, str_detect(colnames(test3), "X4")], 1, function(x)mean(x, na.rm = TRUE))
test3$X5_av <- apply(test3[, str_detect(colnames(test3), "X5")], 1, function(x)mean(x, na.rm = TRUE))
test3$X6_av <- apply(test3[, str_detect(colnames(test3), "X6")], 1, function(x)mean(x, na.rm = TRUE))
test3$X7A_av <-apply(test3[, str_detect(colnames(test3), "X7a")], 1, function(x)mean(x, na.rm = TRUE))
test3$X7B_av <- apply(test3[, str_detect(colnames(test3), "X7b")], 1, function(x)mean(x, na.rm = TRUE))
test3$X8A_av <- apply(test3[, str_detect(colnames(test3), "X8a")], 1, function(x)mean(x, na.rm = TRUE))
test3$X8B_av <- apply(test3[, str_detect(colnames(test3), "X8b")], 1, function(x)mean(x, na.rm = TRUE))
```


```{r, eval = TRUE, fig.height = 2.5, fig.width=3}
vec_col <- c("seagreen4", "darkgoldenrod1", #"brown1", 
             "darkmagenta",
              "dodgerblue2",  "orange", "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3", "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")

bra <- ggplot(test3[test3$Group.1 != "Bradyrhizobium", ], aes(x = X1_av, y = X2_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
   theme(text = element_text(size = 7), legend.position = "none",   axis.title=element_text(size=10)) +
  xlab("SynCom") +
  ylab(expression(italic("- Bradyrhizobium"))) +
  geom_point(aes(x = test3[test3$Group.1 == "Bradyrhizobium", ]$X1_av, y = test3[test3$Group.1 == "Bradyrhizobium", ]$X2_av), color = "brown1", shape = 25, size = 2.5, fill = "brown1") +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

bra
# 
# setwd("/home/moyne/Moyne_disk/Soil_project/Final_datasets/PROBIOTOCS_EXPT_3/")
# ggsave(file="brady_removal.png", plot=bra, height = 2.5, width = 3, dpi = 600)
```


```{r, eval = TRUE, fig.height = 2.5, fig.width=3}
vec_col <- c(#"seagreen4", 
  "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  "orange", "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3", "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")

art <- ggplot(test3[test3$Group.1 != "Arthrobacter", ], aes(x = X1_av, y = X4_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
   theme(text = element_text(size = 7), legend.position = "none",   axis.title=element_text(size=10)) +
  xlab("SynCom") +
  ylab(expression(italic("- Arthrobacter"))) +
  geom_point(aes(x = test3[test3$Group.1 == "Arthrobacter", ]$X1_av, y = test3[test3$Group.1 == "Arthrobacter", ]$X4_av), color = "seagreen4", shape = 25, size = 2.5, fill = "seagreen4") +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

art
# setwd("/home/moyne/Moyne_disk/Soil_project/Final_datasets/PROBIOTOCS_EXPT_3/")
# ggsave(file="arthro_removal.png", plot=art, height = 2.5, width = 3, dpi = 600)
```


```{r, eval = TRUE, fig.height = 2.5, fig.width=3}
vec_col <- c("seagreen4", 
              "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  #"orange", 
             "midnightblue", "deeppink",
           "chartreuse3",#"darkorange2",
           "mediumpurple3", "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")

chimu <- ggplot(test3[!test3$Group.1 %in% c("Chitinophaga", "Mucilaginibacter"), ], aes(x = X1_av, y = X5_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
   geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
   theme(text = element_text(size = 7), legend.position = "none",   axis.title=element_text(size=10)) +
  xlab("SynCom") +
  ylab(expression(italic("- Chitinophaga & Mucilaginibacter"))) +
    geom_point(aes(x = test3[test3$Group.1 == "Chitinophaga", ]$X1_av, y = test3[test3$Group.1 == "Chitinophaga", ]$X5_av), color = "orange", shape = 25, size = 2.5, fill = "orange") +
      geom_point(aes(x = test3[test3$Group.1 == "Mucilaginibacter", ]$X1_av, y = test3[test3$Group.1 == "Mucilaginibacter", ]$X5_av), color = "darkorange2", shape = 25, size = 2.5, fill = "darkorange2") +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=9)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

chimu
  # setwd("/home/moyne/Moyne_disk/Soil_project/Final_datasets/PROBIOTOCS_EXPT_3/")
  # ggsave(file="muci_chiti_removal_noR.png", plot=chimu, height = 2.5, width = 3, dpi = 600)
```

```{r, eval = TRUE, fig.height = 2.5, fig.width=3}
vec_col <- c("seagreen4", 
              "darkgoldenrod1", "brown1", 
             "darkmagenta",
              #"dodgerblue2",  
             "orange", 
             "midnightblue", "deeppink",
           "chartreuse3","darkorange2",
           "mediumpurple3", "mediumvioletred", "cyan3", #"deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")

rhibu <- ggplot(test3[!test3$Group.1 %in% c("Rhizobium", "Burkholderia"), ], aes(x = X1_av, y = X6_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
   theme(text = element_text(size = 7), legend.position = "none",   axis.title=element_text(size=10)) +
  xlab("SynCom") +
  ylab(expression(italic("- Rhizobium & Burkholderia"))) +
    geom_point(aes(x = test3[test3$Group.1 == "Rhizobium", ]$X1_av, y = test3[test3$Group.1 == "Rhizobium", ]$X6_av), color = "deepskyblue4", shape = 25, size = 2.5, fill = "deepskyblue4") +
      geom_point(aes(x = test3[test3$Group.1 == "Burkholderia", ]$X1_av, y = test3[test3$Group.1 == "Burkholderia", ]$X6_av), color = "dodgerblue2", shape = 25, size = 2.5, fill = "dodgerblue2") +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=10)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

rhibu
 # setwd("/home/moyne/Moyne_disk/Soil_project/Final_datasets/PROBIOTOCS_EXPT_3/")
 # ggsave(file="rhizo_burkho_removal_noR.png", plot=rhibu, height = 2.5, width = 3, dpi = 600)
```


```{r, eval = TRUE, fig.height = 3, fig.width=4}
vec_col <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              #"dodgerblue2",  
           "orange", "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3", "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")


ggplot(test3[test3$Group.1 != "Burkholderia", ], aes(x = X1_av, y = X7A_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("Abundance in SynCom (RPKM)") +
  ylab("Abundance in SynCom + Burkholderia x 2 (RPKM)") +
  geom_point(aes(x = test3[test3$Group.1 == "Burkholderia", ]$X1_av, y = test3[test3$Group.1 == "Burkholderia", ]$X7A_av), color = "dodgerblue2", shape = 25, size = 2.5)

ggplot(test3[test3$Group.1 != "Burkholderia", ], aes(x = X1_av, y = X7B_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("Abundance in SynCom (RPKM)") +
  ylab("Abundance in SynCom + Burkholderia x 10 (RPKM)") +
  geom_point(aes(x = test3[test3$Group.1 == "Burkholderia", ]$X1_av, y = test3[test3$Group.1 == "Burkholderia", ]$X7B_av), color = "dodgerblue2", shape = 25, size = 2.5)

```

```{r, eval = TRUE, fig.height = 3, fig.width=4}
vec_col <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  
           "orange", "midnightblue", "deeppink",
           "chartreuse3",#"darkorange2", 
           "mediumpurple3", "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")


ggplot(test3[test3$Group.1 != "Mucilaginibacter", ], aes(x = X1_av, y = X8A_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("Abundance in SynCom (RPKM)") +
  ylab("Abundance in SynCom + Mucilaginibacter x 2 (RPKM)") +
  geom_point(aes(x = test3[test3$Group.1 == "Mucilaginibacter", ]$X1_av, y = test3[test3$Group.1 == "Mucilaginibacter", ]$X8A_av), color = "darkorange2", shape = 25, size = 2.5)

ggplot(test3[test3$Group.1 != "Mucilaginibacter", ], aes(x = X1_av, y = X8B_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("Abundance in SynCom (RPKM)") +
  ylab("Abundance in SynCom + Mucilaginibacter x 10 (RPKM)") +
  geom_point(aes(x = test3[test3$Group.1 == "Mucilaginibacter", ]$X1_av, y = test3[test3$Group.1 == "Mucilaginibacter", ]$X8B_av), color = "darkorange2", shape = 25, size = 2.5)

# maybe a small decrease of Chitinophaga... try higher starting inoculums
```


## Boxplots

We have to compare with "in silico removal" to not be biased by relative abundance

```{r, fig.width=4, fig.height = 3, eval = TRUE}
test3_norm_Muci <- test3[test3$Group.1 != "Mucilaginibacter", ]

#test3_norm_Muci <- test3

test3_norm_Muci[, 2:ncol(test3_norm_Muci)] <- data.frame(apply(test3_norm_Muci[, 2:ncol(test3_norm_Muci)], 2, function(x) x / sum(x)))
test3_norm_Muci <- test3_norm_Muci[, !str_detect(colnames(test3_norm_Muci), "av")]

test3_norm_Muci <- data.frame(cbind(Group.1 = test3_norm_Muci$Group.1, 
                                    test3_norm_Muci[, str_detect(colnames(test3_norm_Muci), "X1")|str_detect(colnames(test3_norm_Muci), "X8"), ]))

rownames(test3_norm_Muci) <- test3_norm_Muci$Group.1
```

```{r}
data_plots <- reshape::melt(test3_norm_Muci)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Sample <- as.character(data_plots$Sample)

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
```

```{r, fig.height = 3, fig.width = 6}
ggplot(data_plots[data_plots$Taxon == "Chitinophaga", ], aes(x = Community, y = count, fill = Taxon)) +
  geom_boxplot() +
    #scale_y_sqrt() 
  scale_fill_manual(values = "orange")

# There might be something here! Test new experiment, higher doses of Mucilaginibacter and see if that works
```

```{r, fig.width=4, fig.height = 3, eval = TRUE}
test3_norm_Burkh <- test3[test3$Group.1 != "Burkholderia", ]

test3_norm_Burkh[, 2:ncol(test3_norm_Burkh)] <- data.frame(apply(test3_norm_Burkh[, 2:ncol(test3_norm_Burkh)], 2, function(x) x / sum(x)))
test3_norm_Burkh <- test3_norm_Burkh[, !str_detect(colnames(test3_norm_Burkh), "av")]

test3_norm_Burkh <- data.frame(cbind(Group.1 = test3_norm_Burkh$Group.1, 
                                    test3_norm_Burkh[, str_detect(colnames(test3_norm_Burkh), "X1")|str_detect(colnames(test3_norm_Burkh), "X7"), ]))

rownames(test3_norm_Burkh) <- test3_norm_Burkh$Group.1
```

```{r}
data_plots <- reshape::melt(test3_norm_Burkh)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Sample <- as.character(data_plots$Sample)

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
```

```{r}
vec_col <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              #"dodgerblue2",  
           "orange", "midnightblue", "deeppink",
           "chartreuse3","darkorange2", 
           "mediumpurple3", "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")
```

```{r, fig.height = 3, fig.width = 6}
ggplot(data_plots[data_plots$Taxon == "Rhizobium", ], aes(x = Community, y = count, fill = Taxon)) +
  geom_boxplot() +
    #scale_y_sqrt() 
  scale_fill_manual(values = "deepskyblue4")

# Same! Try higher concentrations of Burkholderia, maybe we will see Rhizobium going below CI
```


