---
title: "SynCom Community Modifs Abundance Analysis"
author: "Oriane Moyne"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r, message = FALSE}
# Packages I commonly use
library(stringr)
library(ggplot2)
library(FactoMineR)
library(factoextra)
library(reshape)
library(reshape2)
library(gplots)
```

## Data import 

```{r}
# Count tables with taxonomy annotations (Woltka gotu output)
syncom <- read.table("/home/moyne/Moyne_disk/Soil_project/Final_datasets/Probiotics_expt_4_06242022/Probiotics_4_Syncom_formatted_filtered_corrected_RPKM.tsv", 
                    sep="\t", 
                    dec=".", 
                    header = TRUE, 
                    stringsAsFactors = FALSE, 
                    na.strings = NA, 
                    check.names = FALSE, 
                    comment.char = "")
syncom$genus_strain <- str_split(syncom$genus_strain, "_", simplify = TRUE)[,1]

syncom <- syncom[!syncom$genus_strain%in%c("Bacillus", "Terrabacter"), ]
syncom$genus_strain <- str_replace(syncom$genus_strain, "Chitinophagaceae", "Niastella")
```

```{r, eval = FALSE}
PCA(t(syncom[, 4:ncol(syncom)]))
```

## Aggregate by strain

```{r}
syncom_agg <- syncom[, c(3:ncol(syncom))]
syncom_agg <- aggregate(syncom_agg[, 2:ncol(syncom_agg)], by = list(syncom_agg$genus_strain), sum)
```

```{r, eval = TRUE, fig.width=16}
for_pca <- data.frame(t(syncom_agg[, 2:ncol(syncom_agg)]))
colnames(for_pca) <- paste(syncom_agg$Group.1)
                             
pca <- PCA(for_pca)

fviz_pca_ind(pca)
fviz_pca_biplot(pca)
```

```{r, eval = TRUE, fig.width=10}
for_pca <- data.frame(t(syncom_agg[, str_detect(colnames(syncom_agg), "ref")|str_detect(colnames(syncom_agg), "Rhizo")]))
colnames(for_pca) <- paste(syncom_agg$Group.1)
                             
pca <- PCA(for_pca, graph = FALSE)

fviz_pca_biplot(pca, repel = TRUE)
```

```{r, eval = TRUE, fig.width=10}
for_pca <- data.frame(t(syncom_agg[, str_detect(colnames(syncom_agg), "ref")|str_detect(colnames(syncom_agg), "Burkho")]))
colnames(for_pca) <- paste(syncom_agg$Group.1)
                             
pca <- PCA(for_pca, graph = FALSE)

fviz_pca_biplot(pca, repel = TRUE)
```

```{r, eval = TRUE, fig.width=10}
for_pca <- data.frame(t(syncom_agg[, str_detect(colnames(syncom_agg), "ref")|str_detect(colnames(syncom_agg), "Muci")]))
colnames(for_pca) <- paste(syncom_agg$Group.1)
                             
pca <- PCA(for_pca, graph = FALSE)

fviz_pca_biplot(pca, repel = TRUE)
```
```{r, eval = TRUE, fig.width=10}
for_pca <- data.frame(t(syncom_agg[, str_detect(colnames(syncom_agg), "ref")|str_detect(colnames(syncom_agg), "Chiti")]))
colnames(for_pca) <- paste(syncom_agg$Group.1)
                             
pca <- PCA(for_pca, graph = FALSE)

fviz_pca_biplot(pca, repel = TRUE)
```
## Abundance plots


```{r}
data_plots <- reshape::melt(syncom_agg)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Sample <- as.character(data_plots$Sample)

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 3]

data_plots$Concentration <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
data_plots$Concentration <- str_split(data_plots$Concentration, "x", simplify = TRUE)[,1]
data_plots$Concentration[is.na(data_plots$Concentration)] <- "0"
data_plots$Concentration <- ordered(data_plots$Concentration, levels = c("0", "10", "20", "50", "100"))

data_plots <- data_plots[order(data_plots$Concentration), ]
```



```{r, eval = TRUE}
vec_col1 <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  
           "orange",   "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3",  "mediumvioletred","cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")
```


```{r, fig.height=4, fig.width=12}
ggplot(data_plots, aes(fill=Taxon, y=count, x=Sample)) + 
    geom_bar(stat="identity") +
    scale_fill_manual(values = vec_col1) +
    facet_wrap(.~Community, ncol = 6, scales = "free_x") +
   theme(text = element_text(size = 15)) +
  labs(y = "RPKM") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggplot(data_plots, aes(fill=Taxon, y=count, x=Sample)) + 
    geom_bar(stat="identity", position = "fill") +
    scale_fill_manual(values = vec_col1) +
    facet_wrap(.~Community, ncol = 6, scales = "free_x") +
   theme(text = element_text(size = 15)) +
  labs(y = "RPKM") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

#--------------------------------

Correlation between controls

```{r}
test4 <- aggregate(syncom[, 4:ncol(syncom)], by = list(syncom$genus_strain), sum)

# Normalization (optional)
#test4[, 2:ncol(test4)] <- apply(test4[, 2:ncol(test4)], 2, function(x)x/sum(x))

cor(test4[, str_detect(colnames(test4), "ref")])

ggplot(test4, aes(x = SynCom_ref_1, y = SynCom_ref_2)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_manual(values = vec_col1) +
  geom_abline(intercept = 0, slope = 1) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    ##stat_regline_equation(label.y = 500, aes(label = ..rr.label..)) +
    theme(legend.position = "none")  +
  xlab("Control 1") +
  ylab("Control 2") 

```


```{r}
test4 <- aggregate(syncom[, 4:ncol(syncom)], by = list(syncom$genus_strain), sum)

# Normalization (optional)
#test4[, 2:ncol(test4)] <- apply(test4[, 2:ncol(test4)], 2, function(x)x/sum(x))

test4$ref_av <- apply(test4[, str_detect(colnames(test4), "ref")], 1, function(x)mean(x, na.rm = TRUE))

test4$Bu10_av <- apply(test4[, str_detect(colnames(test4), "Burkho_10x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Bu20_av <- apply(test4[, str_detect(colnames(test4), "Burkho_20x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Bu50_av <- apply(test4[, str_detect(colnames(test4), "Burkho_50x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Bu100_av <- apply(test4[, str_detect(colnames(test4), "Burkho_100x")], 1, function(x)mean(x, na.rm = TRUE))

test4$Rhizo10_av <- apply(test4[, str_detect(colnames(test4), "Rhizo_10x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Rhizo20_av <- apply(test4[, str_detect(colnames(test4), "Rhizo_20x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Rhizo50_av <- apply(test4[, str_detect(colnames(test4), "Rhizo_50x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Rhizo100_av <- apply(test4[, str_detect(colnames(test4), "Rhizo_100x")], 1, function(x)mean(x, na.rm = TRUE))

test4$Muci10_av <- apply(test4[, str_detect(colnames(test4), "Muci_10x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Muci20_av <- apply(test4[, str_detect(colnames(test4), "Muci_20x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Muci50_av <- apply(test4[, str_detect(colnames(test4), "Muci_50x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Muci100_av <- apply(test4[, str_detect(colnames(test4), "Muci_100x")], 1, function(x)mean(x, na.rm = TRUE))

test4$Chiti10_av <- apply(test4[, str_detect(colnames(test4), "Chitino_10x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Chiti20_av <- apply(test4[, str_detect(colnames(test4), "Chitino_20x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Chiti50_av <- apply(test4[, str_detect(colnames(test4), "Chitino_50x")], 1, function(x)mean(x, na.rm = TRUE))
test4$Chiti100_av <- apply(test4[, str_detect(colnames(test4), "Chitino_100x")], 1, function(x)mean(x, na.rm = TRUE))

```




```{r}
library(ggpubr)
```


```{r, eval = TRUE, fig.height = 2.5, fig.width=3}
vec_col <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              #"dodgerblue2",  
           "orange",  "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3",  "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")


bu10 <- ggplot(test4[test4$Group.1 != "Burkholderia", ], aes(x = ref_av, y = Bu10_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 500000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Burkholderia "), "x 10"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Burkholderia", ]$ref_av, y = test4[test4$Group.1 == "Burkholderia", ]$Bu10_av), color = "dodgerblue2", fill = "dodgerblue2",  shape = 24, size = 2.5) +
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

bu20 <- ggplot(test4[test4$Group.1 != "Burkholderia", ], aes(x = ref_av, y = Bu20_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 500000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Burkholderia "), "x 20"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Burkholderia", ]$ref_av, y = test4[test4$Group.1 == "Burkholderia", ]$Bu20_av), color = "dodgerblue2", fill = "dodgerblue2",  shape = 24, size = 2.5) +
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

bu50 <- ggplot(test4[test4$Group.1 != "Burkholderia", ], aes(x = ref_av, y = Bu50_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 500000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Burkholderia "), "x 50"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Burkholderia", ]$ref_av, y = test4[test4$Group.1 == "Burkholderia", ]$Bu50_av), color = "dodgerblue2", fill = "dodgerblue2",  shape = 24, size = 2.5) +
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

bu100 <- ggplot(test4[test4$Group.1 != "Burkholderia", ], aes(x = ref_av, y = Bu100_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 500000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Burkholderia "), "x 100"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Burkholderia", ]$ref_av, y = test4[test4$Group.1 == "Burkholderia", ]$Bu100_av), color = "dodgerblue2", fill = "dodgerblue2",  shape = 24, size = 2.5) +
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))


```


```{r, eval = TRUE, fig.height = 2.5, fig.width=3}
vec_col <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  
           "orange",  "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3",  "mediumvioletred",  "cyan3", #"deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")


rhi10 <- ggplot(test4[test4$Group.1 != "Rhizobium", ], aes(x = ref_av, y = Rhizo10_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 350000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Rhizobium "), "x 10"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Rhizobium", ]$ref_av, y = test4[test4$Group.1 == "Rhizobium", ]$Rhizo10_av), color = "deepskyblue4", fill = "deepskyblue4",  shape = 24, size = 2.5)+
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

rhi20 <- ggplot(test4[test4$Group.1 != "Rhizobium", ], aes(x = ref_av, y = Rhizo20_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 350000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Rhizobium "), "x 20"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Rhizobium", ]$ref_av, y = test4[test4$Group.1 == "Rhizobium", ]$Rhizo20_av), color = "deepskyblue4", fill = "deepskyblue4",  shape = 24, size = 2.5) +
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

rhi50 <- ggplot(test4[test4$Group.1 != "Rhizobium", ], aes(x = ref_av, y = Rhizo50_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 350000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Rhizobium "), "x 50"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Rhizobium", ]$ref_av, y = test4[test4$Group.1 == "Rhizobium", ]$Rhizo50_av), color = "deepskyblue4", fill = "deepskyblue4",  shape = 24, size = 2.5) +
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

rhi100 <- ggplot(test4[test4$Group.1 != "Rhizobium", ], aes(x = ref_av, y = Rhizo100_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 350000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Rhizobium "), "x 100"))) +
   geom_point(aes(x = test4[test4$Group.1 == "Rhizobium", ]$ref_av, y = test4[test4$Group.1 == "Rhizobium", ]$Rhizo100_av), color = "deepskyblue4", fill = "deepskyblue4",  shape = 24, size = 2.5) +
      theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

```





```{r, eval = TRUE, fig.height = 3, fig.width=4}
vec_col <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  
           #"orange", 
            "midnightblue", "deeppink",
           "chartreuse3","darkorange2", "mediumpurple3",  "mediumvioletred", "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")


chi10 <- ggplot(test4[test4$Group.1 != "Chitinophaga", ], aes(x = ref_av, y = Chiti10_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE), ) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 600000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Chitinophaga "), "x 10"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Chitinophaga", ]$ref_av, y = test4[test4$Group.1 == "Chitinophaga", ]$Chiti10_av), color = "orange", fill = "orange",  shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

chi20 <- ggplot(test4[test4$Group.1 != "Chitinophaga", ], aes(x = ref_av, y = Chiti20_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 600000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Chitinophaga "), "x 20"))) +
   geom_point(aes(x = test4[test4$Group.1 == "Chitinophaga", ]$ref_av, y = test4[test4$Group.1 == "Chitinophaga", ]$Chiti20_av), color = "orange", fill = "orange",  shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

chi50 <- ggplot(test4[test4$Group.1 != "Chitinophaga", ], aes(x = ref_av, y = Chiti50_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 600000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Chitinophaga "), "x 50"))) +
   geom_point(aes(x = test4[test4$Group.1 == "Chitinophaga", ]$ref_av, y = test4[test4$Group.1 == "Chitinophaga", ]$Chiti50_av), color = "orange", fill = "orange",  shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

chi100 <- ggplot(test4[test4$Group.1 != "Chitinophaga", ], aes(x = ref_av, y = Chiti100_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 600000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Chitinophaga "), "x 100"))) +
 geom_point(aes(x = test4[test4$Group.1 == "Chitinophaga", ]$ref_av, y = test4[test4$Group.1 == "Chitinophaga", ]$Chiti100_av), color = "orange", fill = "orange",  shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))


```

```{r, eval = TRUE, fig.height = 2.5, fig.width=3}
vec_col <- c("seagreen4", 
           "darkgoldenrod1", "brown1", 
             "darkmagenta",
              "dodgerblue2",  
           "orange", 
            "midnightblue", "deeppink",
           "chartreuse3",#"darkorange2", 
           "mediumpurple3", "mediumvioletred",  "cyan3", "deepskyblue4", 
           "orchid3",  
           "green3", "paleturquoise4", "darkgoldenrod", 
           "darkslateblue", "darkseagreen", "hotpink",
           "grey", "black")


mu10 <- ggplot(test4[test4$Group.1 != "Mucilaginibacter", ], aes(x = ref_av, y = Muci10_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 400000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
    #stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Mucilaginibacter "), "x 10"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Mucilaginibacter", ]$ref_av, y = test4[test4$Group.1 == "Mucilaginibacter", ]$Muci10_av), color = "darkorange2", fill = "darkorange2",  shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))

mu20 <- ggplot(test4[test4$Group.1 != "Mucilaginibacter", ], aes(x = ref_av, y = Muci20_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 400000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Mucilaginibacter "), "x 20"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Mucilaginibacter", ]$ref_av, y = test4[test4$Group.1 == "Mucilaginibacter", ]$Muci20_av), color = "darkorange2", fill = "darkorange2",  shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))


mu50 <- ggplot(test4[test4$Group.1 != "Mucilaginibacter", ], aes(x = ref_av, y = Muci50_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 400000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Mucilaginibacter "), "x 50"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Mucilaginibacter", ]$ref_av, y = test4[test4$Group.1 == "Mucilaginibacter", ]$Muci50_av), color = "darkorange2", fill = "darkorange2",  shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +   theme(axis.text.x = element_text(angle = 45, hjust=1))


mu100 <- ggplot(test4[test4$Group.1 != "Mucilaginibacter", ], aes(x = ref_av, y = Muci100_av)) +
  geom_point(aes(color = Group.1), size = 3) +
  scale_x_sqrt(labels = function(x) format(x, scientific = TRUE)) +
  scale_y_sqrt(labels = function(x) format(x, scientific = TRUE), limits = c(-500, 400000)) +
  scale_color_manual(values = vec_col) +
    geom_smooth(method='lm', alpha = 0.5, level = 0.99) +
   # stat_regline_equation(label.y = 700, aes(label = ..rr.label..)) +
     theme(legend.position = "none") +
  xlab("SynCom") +
  ylab(expression(paste(italic("Mucilaginibacter "), "x 100"))) +
  geom_point(aes(x = test4[test4$Group.1 == "Mucilaginibacter", ]$ref_av, y = test4[test4$Group.1 == "Mucilaginibacter", ]$Muci100_av), color = "darkorange2", fill = "darkorange2", shape = 24, size = 2.5) +
        theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

mu100

```


```{r, eval = TRUE, fig.height = 8.5, fig.width=9}
library(cowplot)
setwd("/media/moyne/Moyne_disk/Soil_project/Final_datasets/Probiotics_expt_4_06242022")

probio <- plot_grid(bu10, bu20, bu50, bu100, 
                    rhi10, rhi20, rhi50, rhi100, 
                    mu10, mu20, mu50, mu100, 
                    chi10, chi20, chi50, chi100
                    )
probio

# ggsave(file="probio_syncom_withchiti.png", plot=probio, height = 8, width = 9, dpi = 600)
```


## Boxplots

We have to compare with "in silico removal"

```{r}
test4_bu <- test4[, colnames(test4) == "Group.1" | str_detect(colnames(test4), "Bu") | str_detect(colnames(test4), "ref")]
test4_bu <- test4_bu[test4_bu$Group.1 != "Burkholderia", ]

model <- lm(sqrt(test4_bu$Bu10_av) ~ sqrt(test4_bu$ref_av))
summary(model)
predict(model)
Bu10_pred <- data.frame(cbind(Tax = test4_bu$Group.1, 
                 sqrt_RPKM = sqrt(test4_bu$Bu10_av), 
                 prediction = predict(model)))

Bu10_pred$sqrt_RPKM <- as.numeric(as.character(Bu10_pred$sqrt_RPKM ))
Bu10_pred$prediction <- as.numeric(as.character(Bu10_pred$prediction))
Bu10_pred$Foldchange <- Bu10_pred$sqrt_RPKM / Bu10_pred$prediction
Bu10_pred


model <- lm(sqrt(test4_bu$Bu20_av) ~ sqrt(test4_bu$ref_av))
summary(model)
predict(model)
Bu20_pred <- data.frame(cbind(Tax = test4_bu$Group.1, 
                 sqrt_RPKM = sqrt(test4_bu$Bu20_av), 
                 prediction = predict(model)))

Bu20_pred$sqrt_RPKM <- as.numeric(as.character(Bu20_pred$sqrt_RPKM ))
Bu20_pred$prediction <- as.numeric(as.character(Bu20_pred$prediction))
Bu20_pred$Foldchange <- Bu20_pred$sqrt_RPKM / Bu20_pred$prediction
Bu20_pred

model <- lm(sqrt(test4_bu$Bu50_av) ~ sqrt(test4_bu$ref_av))
summary(model)
predict(model)
Bu50_pred <- data.frame(cbind(Tax = test4_bu$Group.1, 
                 sqrt_RPKM = sqrt(test4_bu$Bu50_av), 
                 prediction = predict(model)))

Bu50_pred$sqrt_RPKM <- as.numeric(as.character(Bu50_pred$sqrt_RPKM ))
Bu50_pred$prediction <- as.numeric(as.character(Bu50_pred$prediction))
Bu50_pred$Foldchange <- Bu50_pred$sqrt_RPKM / Bu50_pred$prediction
Bu50_pred


model <- lm(sqrt(test4_bu$Bu100_av) ~ sqrt(test4_bu$ref_av))
summary(model)
predict(model)
Bu100_pred <- data.frame(cbind(Tax = test4_bu$Group.1, 
                 sqrt_RPKM = sqrt(test4_bu$Bu100_av), 
                 prediction = predict(model)))

Bu100_pred$sqrt_RPKM <- as.numeric(as.character(Bu100_pred$sqrt_RPKM ))
Bu100_pred$prediction <- as.numeric(as.character(Bu100_pred$prediction))
Bu100_pred$Foldchange <- Bu100_pred$sqrt_RPKM / Bu100_pred$prediction
Bu100_pred

bu_predictions_foldchange <- data.frame(cbind(Tax = as.character(Bu10_pred$Tax), x1 = 1, x10 = Bu10_pred$Foldchange, x20 = Bu20_pred$Foldchange, x50 = Bu50_pred$Foldchange, x100 = Bu100_pred$Foldchange))
```


```{r, fig.height = 2.5, fig.width = 3}
data_plots <- reshape::melt(bu_predictions_foldchange, id.var = "Tax")
colnames(data_plots) <- c("Taxon", "Concentration", "FoldChange")
data_plots$FoldChange <- as.numeric(as.character(data_plots$FoldChange))

ggplot(data_plots[data_plots$Taxon == "Rhizobium", ], aes(x = Concentration, y = FoldChange, fill = Taxon, color = Taxon)) +
  geom_boxplot() +
    theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  scale_fill_manual(values = "deepskyblue4") +
    scale_color_manual(values = "deepskyblue4")

ggplot(data_plots[data_plots$Taxon == "Variovorax", ], aes(x = Concentration, y = FoldChange, fill = Taxon, color = Taxon)) +
  geom_boxplot()  +
  theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  scale_fill_manual(values = "green3") +
    scale_color_manual(values = "green3")
```



```{r, fig.width=3, fig.height = 2.5, eval = TRUE}
test4_bu <- test4[, colnames(test4) == "Group.1" | str_detect(colnames(test4), "Bu") | str_detect(colnames(test4), "ref")]
test4_bu <- test4_bu[test4_bu$Group.1 != "Burkholderia", ]

test4_bu[, 2:ncol(test4_bu)] <- data.frame(apply(test4_bu[, 2:ncol(test4_bu)], 2, function(x) x / sum(x)))
test4_bu <- test4_bu[, !str_detect(colnames(test4_bu), "av")]

data_plots <- reshape::melt(test4_bu)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Concentration <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 3]

data_plots$Concentration[data_plots$Community == "SynCom"] <- "1x"
data_plots$Concentration <- ordered(data_plots$Concentration, levels = c("1x", "10x", "20x", "50x", "100x"))

ggplot(data_plots[data_plots$Taxon == "Rhizobium", ], aes(x = Concentration, y = count, fill = Taxon, color = Taxon)) +
  geom_boxplot(alpha = 0.3) +
  ylab("Relative abundance (adjusted)") +       
  theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  scale_fill_manual(values = "deepskyblue4") +
    scale_color_manual(values = "deepskyblue4")

ggplot(data_plots[data_plots$Taxon == "Variovorax", ], aes(x = Concentration, y = count, fill = Taxon, color = Taxon)) +
  geom_boxplot(alpha = 0.3) +
  ylab("Relative abundance (adjusted)") +       
  theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  scale_fill_manual(values = "green3") +
    scale_color_manual(values = "green3")

```


```{r, fig.width=3, fig.height = 2.5, eval = TRUE}
test4_rhi <- test4[, colnames(test4) == "Group.1" | str_detect(colnames(test4), "Rhi") | str_detect(colnames(test4), "ref")]
test4_rhi <- test4_rhi[test4_rhi$Group.1 != "Rhizobium", ]

test4_rhi[, 2:ncol(test4_rhi)] <- data.frame(apply(test4_rhi[, 2:ncol(test4_rhi)], 2, function(x) x / sum(x)))
test4_rhi <- test4_rhi[, !str_detect(colnames(test4_rhi), "av")]

data_plots <- reshape::melt(test4_rhi)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Concentration <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 3]

data_plots$Concentration[data_plots$Community == "SynCom"] <- "1x"
data_plots$Concentration <- ordered(data_plots$Concentration, levels = c("1x", "10x", "20x", "50x", "100x"))

ggplot(data_plots[data_plots$Taxon == "Burkholderia", ], aes(x = Concentration, y = count, fill = Taxon, color = Taxon)) +
  geom_boxplot(alpha = 0.3) +
  ylab("Relative abundance (adjusted)") +       
  theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  scale_fill_manual(values = "dodgerblue2") +
  scale_color_manual(values = "dodgerblue2")

```


```{r, fig.width=3, fig.height = 2.5, eval = TRUE}
test4_chi <- test4[, colnames(test4) == "Group.1" | str_detect(colnames(test4), "Chi") | str_detect(colnames(test4), "ref")]
test4_chi <- test4_chi[test4_chi$Group.1 != "Chitinophaga", ]

test4_chi[, 2:ncol(test4_chi)] <- data.frame(apply(test4_chi[, 2:ncol(test4_chi)], 2, function(x) x / sum(x)))
test4_chi <- test4_chi[, !str_detect(colnames(test4_chi), "av")]

data_plots <- reshape::melt(test4_chi)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Concentration <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 3]

data_plots$Concentration[data_plots$Community == "SynCom"] <- "1x"
data_plots$Concentration <- ordered(data_plots$Concentration, levels = c("1x", "10x", "20x", "50x", "100x"))


ggplot(data_plots[data_plots$Taxon == "Mucilaginibacter", ], aes(x = Concentration, y = count, fill = Taxon, color = Taxon)) +
  geom_boxplot(alpha = 0.3) +
  ylab("Relative abundance (adjusted)") +       
  theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  scale_fill_manual(values = "darkorange2") +
  scale_color_manual(values = "darkorange2")

```

```{r, fig.width=3, fig.height = 2.5, eval = TRUE}
test4_muc <- test4[, colnames(test4) == "Group.1" | str_detect(colnames(test4), "Muci") | str_detect(colnames(test4), "ref")]
test4_muc <- test4_muc[test4_muc$Group.1 != "Mucilaginibacter", ]

test4_muc[, 2:ncol(test4_muc)] <- data.frame(apply(test4_muc[, 2:ncol(test4_muc)], 2, function(x) x / sum(x)))
test4_muc <- test4_muc[, !str_detect(colnames(test4_muc), "av")]

data_plots <- reshape::melt(test4_muc)
colnames(data_plots) <- c("Taxon", "Sample", "count")

data_plots$Community <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 1]
data_plots$Concentration <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 2]
data_plots$Replicate <- str_split(data_plots$Sample, "_", simplify = TRUE)[, 3]

data_plots$Concentration[data_plots$Community == "SynCom"] <- "1x"
data_plots$Concentration <- ordered(data_plots$Concentration, levels = c("1x", "10x", "20x", "50x", "100x"))


ggplot(data_plots[data_plots$Taxon == "Chitinophaga", ], aes(x = Concentration, y = count, fill = Taxon, color = Taxon)) +
  geom_boxplot(alpha = 0.3) +
  ylab("Relative abundance (adjusted)") +       
  theme(legend.position = "none", panel.background = element_rect(fill = "white"), panel.grid.major = element_line(colour = "gray92"), panel.grid.minor = element_line(colour = "gray95"))  +
    theme(axis.text=element_text(size=8), axis.title=element_text(size=11)) +
  scale_fill_manual(values = "orange") +
  scale_color_manual(values = "orange")

```


